[package]
name = "min-rs"
version = "0.1.0"
authors = ["qianchenzhumeng <qianchenzhumeng@live.cn>"]
description = "The MIN(Microcontroller Interconnect Network) protocol Rust Library."
edition = "2018"

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
